instrumentation:
    root: src/js
    excludes: ["**/__tests__/**"]
reporting:
    dir: ./reports/coverage
    watermarks:
        statements: [50, 80]
        lines: [50, 80]
        functions: [50, 80]
        branches: [50, 80]
